refactor all

diff --git a/diag-storage-disk b/diag-storage-disk
--- a/diag-storage-disk
+++ b/diag-storage-disk
@@ -1,146 +1,145 @@
 #!/bin/bash
+# Copyright (C) 2024 Evgeny Sinelnikov <sin@altlinux.org>
+# Copyright (C) 2024 Andrey Limachko <liannnix@altlinux.org>
+# Copyright (C) 2024 Elena Dyatlenko <lenka@altlinux.org>
 #
-# Copyright (c) 2024 Evgeny Sinelnikov <sin@altlinux.org>
+# The Storage Disk Status Diagnostic Utility
 #
-# Disks diagnostic tool
+# This program is free software: you can redistribute it and/or modify
 #
-# SPDX-License-Identifier: GPL-2.0-or-later
-#
-
-#trap 'echo "# $BASH_COMMAND";read' DEBUG
+# SPDX-License-Identifier: GNU GPL v3.0
 
 set -euo pipefail
 
 . shell-getopt
 
-PROG="${0##*/}"
-PROG_VERSION='0.0.1'
-task_list="$*"
-
-cmd="run"
+PROG_NAME="${0##*/}"
+VERSION="0.0.1"
 global_retval=0
+task_list="$*"
+cmd="run"
 DISKS=""
 
-# Display the program version
-print_version()
-{
+print_version() {
 	cat <<EOF
-$PROG version $PROG_VERSION
-Written by Elena Dyatlenko <lenka@altlinux.org>
-
-Copyright (C) 2024 Elena Dyatlenko <lenka@altlinux.org>
-This is free software; see the source for copying conditions.  There is NO
-warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
+$PROG_NAME version $VERSION
 EOF
-	exit
+	exit 0
 }
 
-# Function for showing help
-show_usage()
-{
+show_usage() {
 	cat <<EOF
-$PROG - disks diagnostic tool.
+$PROG_NAME - Storage disks diagnostic tool.
 
-Usage: $PROG [options] [<diagnostic-task>]
+Usage: $PROG_NAME [options] [<diagnostic-task>]
 
 Options:
-  -l, --list                list of diagnostic tasks;
-  -V, --version             print program version and exit;
-  -h, --help                show this text and exit.
-
-Report bugs to https://bugzilla.altlinux.org/
-
+	-l, --list			list of diagnostic tasks
+	-V, --version		print program version and exit
+	-h, --help			show this text and exit
 EOF
-	exit
+	exit 0
 }
 
-TEMP=$(getopt -n "$PROG" -o "l,V,h" -l "list,version,help" -- "$@") || show_usage
+TEMP=$(getopt -n "${0##*/}" -o "l,V,r,h", -l "list,version,report,help" -- "$@") || show_usage
 eval set -- "$TEMP"
 
 while :; do
 	case "$1" in
-		--) shift; break
+		-l|--list)
+			cmd="list"
+			shift
 			;;
-		-l|--list) cmd="list";
+		-V|--version)
+			print_version
+			shift
 			;;
-		-V|--version) print_version
+		-r|--report)
+			shift
 			;;
-		-h|--help) show_usage
+		-h|--help)
+			show_usage
+			shift
 			;;
-		*) fatal "Unrecognized option: $1"
+		--)
+			shift
+			break
+			;;
+		*)
+			fatal "Unrecognized option: $1"
 			;;
 	esac
-	shift
 done
 
-# Display a list of tests
-task_show()
-{
+task_show() {
 	local func="$1"
-
 	echo "$func"
 }
 
-# Run the tests
-task_run()
-{
+task_run() {
 	local retval=126
 	local func="$1"
+
 	if test -n "$task_list"; then
-		echo "$task_list" | tr ' ' '\n' | grep -q "^$func\$" ||
-			return 0
+		echo "$task_list" | tr ' ' '\n' | grep -q "^$func\$" || return 0
 	fi
+
 	$func && retval=0 || retval="$?"
 	test $retval = 0 || global_retval=1
+
 	return $retval
 }
 
-# Display the test execution status
-test_status()
-{
-	case "$1" in
-		0) echo "[DONE]: $2"
-		;;
-		1) echo "[FAIL]: $2"
-		;;
-		2) echo "[WARNING]: $2"
-		;;
-		*) echo "[FAIL]: $2"
+# Determining the test execution status
+test_status() {
+	local retval="$1"
+	local task="$2"
+
+	case "$retval" in
+		0) echo "[DONE]: $task"
+			;;
+		1) echo "[FAIL]: $task"
+			;;
+		2) echo "[WARN]: $task"
+			;;
+		*) echo "[FAIL]: $task"
+			;;
 	esac
 }
 
-# Launch the selected program module (list, run)
-task()
-{
+# Depending on the parameter of the cmd variable, the function decides what to run
+task() {
 	local task="$1"
+
 	case "$cmd" in
 		list)
 			task_show "$task"
-		;;
+			;;
+		report)
+			;;
 		run)
 			if test -z "$task_list" || grep "$task" <<< "$task_list"; then
-				local result=0
-				task_run "$task" || result=$?
-				test_status "$result" "$task"
+				local retval=0
+
+				task_run "$task" || retval="$?"
+				test_status "$retval" "$task"
 			fi
-		;;
+			;;
 		*)
 			fatal "Unrecognized command: $cmd"
-		;;
+			;;
 	esac
 }
 
 # Get a list of system disks
-get_disks()
-{
+get_disks() {
 	local retval=0
 	DISKS=$(smartctl --scan | grep -E -o '/dev/[^[:space:],]+' | sort | uniq) || retval=1
 	return "$retval"
 }
 
 # Verification whether this machine is virtual
-is_vm()
-{
+is_vm() {
 	local retval=0
 	echo ================================
 	hostnamectl | grep -i virtualization || retval=1
@@ -154,8 +153,7 @@ is_vm()
 }
 
 # Display a list of system disks
-view_disks()
-{
+view_disks() {
 	local retval=0
 	echo ================================
 	lsblk || retval=1
@@ -164,8 +162,7 @@ view_disks()
 }
 
 # Display the disk type
-view_disk_type()
-{
+view_disk_type() {
 	local retval=0
 	echo ================================
 	smartctl --scan
@@ -174,8 +171,7 @@ view_disk_type()
 }
 
 # Display disk information using the smartctl utility
-view_adout_disk()
-{
+view_adout_disk() {
 	local retval=0
 	echo ================================
 	get_disks || retval=1
@@ -188,8 +184,7 @@ view_adout_disk()
 }
 
 # Check SMART support
-check_support_smart()
-{
+check_support_smart() {
 	local retval=0
 	echo ================================
 	get_disks || retval=1
@@ -205,8 +200,7 @@ check_support_smart()
 }
 
 # Display detailed information about the disk status using the smartctl utility
-view_about_disk_status()
-{
+view_about_disk_status() {
 	local retval=0
 	echo ================================
 	get_disks || retval=1
@@ -219,8 +213,7 @@ view_about_disk_status()
 }
 
 # Display the result of the disk health check using the smartctl utility
-view_disk_health()
-{
+view_disk_health() {
 	local retval=0
 	echo ================================
 	get_disks || retval=1
@@ -233,8 +226,7 @@ view_disk_health()
 }
 
 # Begin an extended self-test of disks (short)
-short_test_smartctl()
-{
+short_test_smartctl() {
 	local retval=0
 	echo ================================
 	get_disks || retval=1
@@ -248,8 +240,7 @@ short_test_smartctl()
 }
 
 # Display the Self Test Error Log
-view_tests_smartctl()
-{
+view_tests_smartctl() {
 	local retval=0
 	echo ================================
 	get_disks || retval=1
